version: "3.8"
services:
    database:
        image: mysql:latest
        ports:
            - "3306:3306"
#        command: --init-file ./init.sql
#        volumes:
#            - ./init.sql:/data/application/init.sql
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: course3db
            MYSQL_USER: test
            MYSQL_PASSWORD: test
